### ISSUE TITLE
Contact Box

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#114]
@rjbain feedback for the contact box:

http://dev-dgreat.pantheonsite.io/student-life/casa/

Did not include a link to Schedule an Appointment but the button displayed anyways.  Also the other contact boxes on the page have the button as well and all of them go to the CASA home page, even though nothing has been configured.

When adding a contact box block to the block layout.  You need to include the urls that the block apprears or it defaults to showing on every page.  Can we set the the radio button to "hide for the listed pages" by default?

**Comment by sozguzer** [comment]
Issues I've found:
1)  Email/phone/fax need a wrapper around them to give a margin-bottom and be able to make that section two column on tablet. (might want to put one around social media buttons too) 

2)  Google Plus and Tumblr class names are written wrong so they don't show correctly. Correct ones are .googleplus and .tumblr

3)  fax number doesn't show up. Address have br tags because address box 2 and 3 doesn't show up

**Comment by drmyers1** [comment]
@sozguzer thank you for additional feedback.  @rjbain i moved this to the current sprint column.

**Comment by sozguzer** [comment]
Duplicate id in Contact box code. 1st and 3rd div has the same id "block-myusf-contactbox":

<aside class="section" role="complementary">
<div data-quickedit-entity-id="block_content/15" id="block-myusf-contactbox" class="contextual-region settings-tray-editable" data-drupal-settingstray="editable" data-quickedit-entity-instance-id="0">   
    <div data-contextual-id="block:block=casacontactbox:has_overrides=0&amp;langcode=en|settings_tray::langcode=en|block_content:block_content=15:changed=1527710833&amp;langcode=en" class="contextual" role="form">...........</div>
    <div data-quickedit-entity-id="block_content/15" id="block-myusf-contactbox" class="contextual-region settings-tray-editable block block-block-content block-block-content4b46f387-5741-479f-9112-e256fa6ca299" data-drupal-settingstray="editable" data-quickedit-entity-instance-id="1">
        <h2>Center for Academic and Student Achievement (CASA)</h2>
        ....
     </div>
</div>
</aside>

**Comment by drmyers1** [comment]
@rjbain is there a way to confirm if it is a config_ignore setup issue?

**Comment by rjbain** [comment]
@drmyers1 I see them now. After some more testing, it looks like it's working, but I needed to clear the cache to see the changes.

**Comment by drmyers1** [comment]
@rjbain that is good news.  Can you add in the changes that @sozguzer has listed above?

**Comment by drmyers1** [comment]
@sozguzer can you please provide any notes on your QA so that we can confirm the work is complete?

@rjbain we may have to look at more granular caching but I will add to the list to discuss as a team.

**Comment by sozguzer** [comment]
Issue 2 is still an issue. Google Plus and Tumblr class names are written wrong so they don't show correctly. Correct ones are .googleplus and .tumblr
PS: In the dropdown where you select the social media buttons, Tumblr is spelled Tumbler

**Comment by drmyers1** [comment]
@sozguzer thank you for the feedback.  Moving to new projects until we can get this rescheduled.

**Comment by rjbain** [comment]
@drmyers1 drupal isn't letting me change those values because there's data already in the db for that field. I'll have to think about how to deal with it.

**Comment by sozguzer** [comment]
Another issues Tom and I found: 
1) If you don't fill out Address Box 2, the br tags before and after it is still there so there is too much space between Address Box 1 and 3.
2) Hours of Operation should have two separate fields: date and hrs so, as in some cases, we don't have just the AM or PM going to the next line
<img width="250" alt="screen shot 2018-06-13 at 10 26 42 am" src="https://user-images.githubusercontent.com/37126629/41367707-ad0cccd6-6ef4-11e8-85a3-5db421295f93.png">

**Comment by drmyers1** [comment]
@sozguzer thanks for the feedback.  We will get this scheduled.

**Comment by tomkhenke** [comment]
Other issue was mentioned but I didn't see a card so adding it here:

Need to remove the text for each of fields: Tel, Fax, Email. That text is coming from the component, but the CSS is adding the icons automatically and that's enough.

**Comment by nicholas-kebbas** [comment]
Ampersands are showing up as &amp;

**Comment by drmyers1** [comment]
We also need to make sure that the body section is pulled in, if there is content.  Here is an example of page contact box that has text in the body field:
https://live-dgreat.pantheonsite.io/special-events
https://live-dgreat.pantheonsite.io/block/277?destination=node/137665

**Comment by mjuarez2** [comment]
@nicholas-kebbas @rjbain @sozguzer @drmyers1 Contact box changes are live on live-dgreat.pantheonsite.io

**Comment by drmyers1** [comment]
@mjuarez2 i am noticing that the basic content that is getting pulled in is not coming in with the html.  email addresses are not linked and line breaks are not working.  is there a way to fix this?  Here is an example:
https://live-dgreat.pantheonsite.io/arts-sciences/physics-astronomy

**Comment by mjuarez2** [comment]
@nicholas-kebbas @drmyers1  This is now on https://pr-250-dgreat.pantheonsite.io

**Comment by drmyers1** [comment]
@mjuarez2 this looks to be working.

**Comment by nicholas-kebbas** [comment]
@mjuarez2 looks good
