### ISSUE TITLE
Basic Pages

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#115]
Page titles are not showing up for basic pages.  See the following example:
http://dev-dgreat.pantheonsite.io/student-life/casa/mission-vision

Because page title will be used for the title of the page, we need to have an administrative title.  It will get really confusing if we have multiple pages using the same name like "About Us."

**Comment by drmyers1** [comment]
@tomkhenke would like to see if we can create a toggle to show the title or hide for a website homepage.  

-one concern is that we need the H1 for the page.

**Comment by drmyers1** [comment]
@tomkhenke would like to see if we can create a toggle to show the title or hide for a website homepage.  

-one concern is that we need the H1 for the page name.  Do we include in the code only for titles that are hidden?

**Comment by drmyers1** [comment]
@rjbain to create display title field to use for page title and the original title will become admin title.

**Comment by rjbain** [comment]
@drmyers1 I added the new Display Title field to this branch, and adjusted the migration so it gets populated with the Title from the old site. I'm going to edit the basic page template to pull in the Display Title as an h1 next:
https://pr-disp-dgreat.pantheonsite.io/node/139676/edit

**Comment by drmyers1** [comment]
@rjbain the display title looks good within the Basic page edit screen.

**Comment by rjbain** [comment]
@drmyers1 I created a template to pull in the new Display Title as an h1 on the front end. I also added some sass that Selin sent me. I think it's ready to merge. Could you have a look? Thanks.

**Comment by drmyers1** [comment]
@rjbain this looks good.  Was able to edit and see title on view.

**Comment by rjbain** [comment]
@drmyers1 this is on dev now.
