### ISSUE TITLE
Footer for Non-Authenticated Users

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#118]
The footer does not display for non authenticated users.

http://dev-dgreat.pantheonsite.io/student-life/casa

**Comment by drmyers1** [comment]
@rjbain pulling this out of current sprint and will reschedule

**Comment by sozguzer** [comment]
This is what Micheal had said:
mjuarez2 [1:40 PM] May 30th
I think I understand now.
The footer is a menu type object.
Officially, there are no links in this menu, so it assumes it should not display
Which makes sense.
Actually, in the footer, all the links are hard coded.
So, I moved the HTML content to a simple block type element, created a template in blocks, and placed it on the footer, now it showss
We'll probably have to do that at some point, or just tie it into the menu system

**Comment by drmyers1** [comment]
@sozguzer thanks for including Michael's notes.

**Comment by nicholas-kebbas** [comment]
Not showing up anywhere currently

**Comment by nicholas-kebbas** [comment]
Also need to remove "Contact" and "Policies" from footer
