### ISSUE TITLE
Setup and Configure myUSF Search

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#132]
We need to set up and configure google search on myUSF.  The search will need to have the same options as on the current myUSF.  Search content only on myUSF or Search both myUSF and the Marketing site.

**Comment by drmyers1** [comment]
@mjuarez2 i tested search and i see it pulling in myUSF results but I dont see marketing content.  Can you confirm that this is working?

**Comment by nicholas-kebbas** [comment]
@mjuarez2 @drmyers1 Hi Michael it looks to be working now

**Comment by drmyers1** [comment]
@mjuarez2 this is working now.  I see results for both myUSF and www.
