### ISSUE TITLE
Microsite Quicklinks

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#133]
We need to create a quicklink custom block type to display microsite quicklinks.

**Comment by rjbain** [comment]
@drmyers1 Here's a link to the quick links block type I created. Could you take a look? Thanks.
https://pr-133-dgreat.pantheonsite.io/student-life/casa

**Comment by drmyers1** [comment]
@rjbain i tried to access the branch but i get a 404.  was this merged already?

**Comment by rjbain** [comment]
@drmyers1 yes, it's on dev now:
http://dev-dgreat.pantheonsite.io/student-life/casa

**Comment by rjbain** [comment]
@drmyers1 I added the css class and now the quick links are being styled. I merged it to dev: http://dev-dgreat.pantheonsite.io/student-life/casa
