### ISSUE TITLE
Web Content Import

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#140]
@rjbain this is the card for importing content into your new multidev and then working with Dustin to merge and test the results in Tandem2.

**Comment by rjbain** [comment]
@drmyers1 I deleted all the nodes on pr-tandem2 and now we just need Dustin to migrate the users. when that's done, I'll do the node migration and we'll continue from there.

**Comment by drmyers1** [comment]
@rjbain I was not able to find an example of a page that was part of your import that included links to PDFs.  Is it possible to import more nodes?

Also, it seems like all our test content that was created on dev was also migrated. 

I also see that we are pulling in the images into the webpages.  What steps do we need to take to ensure those dont come over with the content scrape?

**Comment by rjbain** [comment]
@drmyers1 I'm going to do a scrape of 600 pages. I'll update the script to scrub out image references too.  I still don't know why the test content is there. @dustinleblanc I deleted some of the test pages and ran `lando drush cim` to see if they would be recreated and they weren't. I was using a combination of `devel genc --kill` and the `delete_all` module to delete them. Nothing was listsed on the `/admin/content` screen when I began the migration, so I don't know how they survived.

**Comment by rjbain** [comment]
@drmyers1 After the most recent migration, I don't see the test content from dgreat dev any more.

**Comment by rjbain** [comment]
[urls-myusf-kill5.txt](https://github.com/rjbain/dgreat/files/2138884/urls-myusf-kill5.txt)
@drmyers1 Here are the urls I scraped.

**Comment by rjbain** [comment]
@drmyers1 I'm using rsync to upload the files. It's working:
http://pr-tandem4-dgreat.pantheonsite.io/admin/content/files?filename=&filemime=application%2Fpdf&status=All

**Comment by rjbain** [comment]
@drmyers1 All the files should be uploaded now to pr-tandem4

**Comment by rjbain** [comment]
@drmyers1 I ran into an issue with the user deletions. John is helping to figure out why it's not deleting any more (still have ~19k to delete).

**Comment by rjbain** [comment]
@drmyers1 I was able to delete the old users using John's module, but it did take hours to finish deleting them.
