### ISSUE TITLE
Favorite Apps - Restrict Non-Admins to Not be able to View Preferences, not be able to add favorite app

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#160]

**Comment by nicholas-kebbas** [comment]
Hide "All Apps" from Favorite Links page

**Comment by nicholas-kebbas** [comment]
Rename Fave Apps to Top Apps. 
On https://pr-dshblks2-dgreat.pantheonsite.io/quick-links change to "myLinks" and "all Links"

**Comment by nicholas-kebbas** [comment]
@mjuarez2 Hey Michael can you work on these fixes after you finish the template override/other pieces of the dashboard?

**Comment by mjuarez2** [comment]
@nicholas-kebbas @drmyers1 This change is on https://pr-229-dgreat.pantheonsite.io Make sure to clear ur local caches

**Comment by drmyers1** [comment]
@mjuarez2 this looks good
