### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#166]
@mjuarez2 There is an html change for the accordions to work properly.  @sozguzer do you have any additional information that you can provide?

**Comment by sozguzer** [comment]
On the marketing site, after the h3 for the accordion title there is a span tag <span class="faq_list_question_symbol"></span>. The diamond-link is attached to that. 

If we can add something like <span class="accordion-button"></span> it will solve the problem

EX: https://www.usfca.edu/arts-sciences/graduate-programs/data-science/faqs

**Comment by mjuarez2** [comment]
Discussed with @sozguzer. ATM cannot add tags to paragraphs since these are not done using theme templates.

**Comment by sozguzer** [comment]
For now I'll just have the arrow so it will be ready for training. We can try to figure out something else later
