### ISSUE TITLE
Block Layout Issues

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#175]
Need to come up with a solution on how to restrict the display of menus on pages with nested aliases. For example, /student-life/casa displays the student life menu and quick links, as well as the CASA main menu and quick links, currently.  

We want it to only display the CASA Quick Links and Main Menu.

**Comment by nicholas-kebbas** [comment]
Some solutions here: https://drupal.stackexchange.com/questions/170002/how-to-display-a-block-on-only-the-listed-pages-using-wildcard-and-excluding-sub

**Comment by nicholas-kebbas** [comment]
This seems to be the best module to fix this issue: https://www.drupal.org/project/block_exclude_pages

**Comment by rjbain** [comment]
Thanks for finding this @nicholas-kebbas

**Comment by nicholas-kebbas** [comment]
Moving to closed because we can solve this with block visibility groups
