### ISSUE TITLE
Calendar/Home Slider Issues

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#187]
- Text Itself isn't a link, only the top half of the slider links out.
- Marlene says slider image is too large, so we'll want to talk about making that smaller.

**Comment by tomkhenke** [comment]
I'm not seeing an anchor region defined in the CSS that would explain the link only being on half the image. Maybe it's a bootstrap definition?

One more issue is we will need a way to change the number of items in the slider, in a way that's flexible. I'd think something like 5 items is more sensible than the 3 that are there now

**Comment by drmyers1** [comment]
@sozguzer has added to her list to look at changing the css.

**Comment by mjuarez2** [comment]
@tomkhenke @drmyers1 @sozguzer @nicholas-kebbas Featured events are currently set to display 10 items

**Comment by sozguzer** [comment]
I can't figure out why the link is not working. Not sure if it is a css issue. The link is around the image but when i give it a border it doesn't even show up.

**Comment by drmyers1** [comment]
@mjuarez2 @rjbain do either of you have any suggestions for fixing the event slider?  currently none of them link to the event details.

**Comment by sozguzer** [comment]
Michael found out that a div class in the template was blocking clicking. I am looking into seeing what will happen CSS-wise if we take it out and whether it breaks anything else.

**Comment by drmyers1** [comment]
moving this card to closed.
