### ISSUE TITLE
Login Box

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#203]
@mjuarez2 we need to change the login box from going to user/login to directly going to the cas login page. 

We would also like to change the behavior after a user a logged in.  Right now it replaces the login button with a logout button.  Can replace the logout button with the users name (similar behavior that you see in the current myUSF)?  We would also like to have have drop down that has a link to the dashboard, myApps and logout.  The myApps will go to the new ITS IAM system (will get you link).

If this functionality too difficult to set up we will move the work to post launch.  Can you let me know if you think this is possible?

**Comment by mjuarez2** [comment]
@drmyers1 @sozguzer This has been added to https://pr-dshblks2-dgreat.pantheonsite.io/
