### ISSUE TITLE
"Menu" showing up on all submenus

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#216]
Something changed and the "Menu" button is now appearing on all views, not just mobile.

![Screen Shot 2018-07-16 at 9.41.38 AM.png](https://images.zenhubusercontent.com/5afdbb894b5806bc2bd3979f/b9b20862-c85f-4738-a5ca-2fecb1ad9ee9)

**Comment by nicholas-kebbas** [comment]
@mjuarez2 This happened when the "aggregate javascript" box was checked on the caching page. It also seems to have broken the WYSIWYG media browser

**Comment by drmyers1** [comment]
@mjuarez2 when you uncheck the aggregate javascript, we also want to reducing caching to 15 mins while we are still working on the site.  we can increase back when we launch.

**Comment by mjuarez2** [comment]
@drmyers1 @nicholas-kebbas Turning off JS aggregation has fixed this. This is on live.
