### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#220]
Need a better 404 page

**Comment by drmyers1** [comment]
@rjbain could you look at this

**Comment by rjbain** [comment]
@drmyers1 Sure, what do we want on the page?

**Comment by drmyers1** [comment]
can we do something to what we have on the live site?

**Comment by rjbain** [comment]
Sure, so just change the text on the page?

Rob Bain
Web Developer
University of San Francisco
Web Services

**Comment by drmyers1** [comment]
@rjbain yes, change the text and maybe include a link to the search.

**Comment by rjbain** [comment]
@drmyers1 I have the 404 page configured here:
https://pr-293-dgreat.pantheonsite.io/blah
I also have the registration settings change there too.

**Comment by drmyers1** [comment]
@nicholas-kebbas could you test the 404 and registration today for @rjbain

**Comment by rjbain** [comment]
@nicholas-kebbas you can see that the registration tab is gone here: https://pr-293-dgreat.pantheonsite.io/user/login

**Comment by nicholas-kebbas** [comment]
@rjbain looks good thanks rob

**Comment by rjbain** [comment]
This is live @nicholas-kebbas

**Comment by drmyers1** [comment]
@rjbain had Marlene take a look at the 404 page.  Can we change the title "Page Not Found" to "404 Error"?  Is it possible to add the search box on the page, like we do on the marketing site?

**Comment by rjbain** [comment]
@drmyers1 Sure, I can do that.

**Comment by rjbain** [comment]
@drmyers1 is it ok to have the alias be "/page-not-found"?

**Comment by rjbain** [comment]
@drmyers1 I have it up for review here:
https://pr-316-dgreat.pantheonsite.io/blah

**Comment by drmyers1** [comment]
@rjbain this looks good.  search worked for me.

**Comment by rjbain** [comment]
@drmyers1 Should I merge? I have the robots.txt changes up on this branch too. Thanks.

**Comment by drmyers1** [comment]
@rjbain yes, i think we should merge.

**Comment by rjbain** [comment]
@drmyers1 This is live now. Robots.txt didn't take again. I tried to SFTP it and keep getting permission denied errors. I'm following up with support.
