### ISSUE TITLE
Quick Links (Nick's Links) View Links are switched/not working

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#223]
The "+" icon on the quick links view on the dashboard goes to manage quick links, when it should go to add. The pencil icon goes to add but the link is incorrect (it should go to /quick-links).

**Comment by mjuarez2** [comment]
@nicholas-kebbas This is on https://pr-229-dgreat.pantheonsite.io

**Comment by drmyers1** [comment]
@mjuarez2 this looks good.
