### ISSUE TITLE
Open Link in New Window - For links added in WYSIWYG

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#232]
Currently you can not create a link that opens in a new window without going in the code.  We want to include the option in the editor.

**Comment by rjbain** [comment]
@drmyers1 @nicholas-kebbas Do we want to add Linkit functionality as well, so people can search for nodes to link to?

**Comment by rjbain** [comment]
@drmyers1 @nicholas-kebbas I added Linkit. Could you take a look? It has an option for opening the link in a new window and you can search for nodes to link to: https://pr-243-dgreat.pantheonsite.io/node/48592/edit

**Comment by nicholas-kebbas** [comment]
@rjbain Looks to work well

**Comment by rjbain** [comment]
Ok, I'll merge
