### ISSUE TITLE
Add Favicon 

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#233]
Add favicon.ico to new myUSF site:  https://live-dgreat.pantheonsite.io/admin/appearance/settings

We want to use the one currently on myUSF

**Comment by mjuarez2** [comment]
@nicholas-kebbas @drmyers1 This is on https://pr-229-dgreat.pantheonsite.io

**Comment by drmyers1** [comment]
@mjuarez2 this looks good.
