### ISSUE TITLE
Quick Links Relative URLS point to "internal" & open in new window feature

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#235]
For some reason, links created using relative URLs don't work as expected and instead point to "internal"

Seperately, we'd like a checkbox that allows the option to make the link open in a new window.

**Comment by rjbain** [comment]
Could someone take a quick look here?
https://pr-240-dgreat.pantheonsite.io/
I think it should be fixed

**Comment by drmyers1** [comment]
@rjbain this looks be working for me.

**Comment by rjbain** [comment]
@drmyers1 @nicholas-kebbas Can you take a look here? https://pr-346-dgreat.pantheonsite.io/
You should be able to configure the quick links to open in a new window. Thanks.

**Comment by nicholas-kebbas** [comment]
@rjbain Looks good
