### ISSUE TITLE
Events Calendar - Make category search default to all dates

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#236]

**Comment by nicholas-kebbas** [comment]
Right now when you search for a category it defaults to the current day and nothing shows up

**Comment by drmyers1** [comment]
@mjuarez2 could you look at this request?

**Comment by mjuarez2** [comment]
@drmyers1 @nicholas-kebbas This is on pr-245-dgreat.pantheonsite.io

**Comment by drmyers1** [comment]
@mjuarez2 @nicholas-kebbas i was not able to access the branch.  Did this change get merged?

**Comment by nicholas-kebbas** [comment]
@mjuarez2 @drmyers1 Ah this card already exists. I'll delete the card I made. Yeah Michael this doesn't seem to have made it up to live and your multidev seems to have been deleted.

**Comment by mjuarez2** [comment]
@nicholas-kebbas @drmyers1 This is now on https://pr-250-dgreat.pantheonsite.io

**Comment by drmyers1** [comment]
@mjuarez2 this looks to be working.  If I search with other categories and get no results, does that mean that they dont have any upcoming events?  I tried Arts and Sciences

**Comment by mjuarez2** [comment]
@drmyers1 Normally yeah. I did College of Arts and Sciences from the dropdown and got a number of results from Sport Management https://pr-250-dgreat.pantheonsite.io/calendar?action=search&search_content=&event_category=5&event_date=

**Comment by drmyers1** [comment]
@mjuarez2 thanks.  i guess i clicked it incorrectly.  Can we push your changes forward or is  there anything else we need to test of pr-250

**Comment by nicholas-kebbas** [comment]
@mjuarez2 this also looks good
