### ISSUE TITLE
Homepage, make title text not required, remove black border around subtitle 

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#238]
- Black border is probably because the homepage is pulling in a <br> tag

**Comment by nicholas-kebbas** [comment]
@mjuarez2  Tom said to let him know if the black border is CSS and they'll take care of it

**Comment by mjuarez2** [comment]
@nicholas-kebbas @drmyers1 The home page is a basic page, so if the title is not required, that will also be the case for all basic pages. Let me know if that's ok.

Black border issue is on live

**Comment by nicholas-kebbas** [comment]
@mjuarez2 Thanks Michael. For now I'd say keep it required, then.

**Comment by nicholas-kebbas** [comment]
@mjuarez2 Actually Michael to revisit this one, I just mean the "Welcome to myUSF" part. Can you make the Title not required on the Hero Image Content type?  https://live-dgreat.pantheonsite.io/node/140135/edit?destination=/admin/content%3Ftitle%3D%26type%3Dhero_image%26status%3DAll%26langcode%3DAll

**Comment by mjuarez2** [comment]
@nicholas-kebbas Title is required by default. If we want to make the title optional on display, we can add a display title field and use that instead. Easy set up. Lemme know.

**Comment by nicholas-kebbas** [comment]
@mjuarez2 Yes please let's do that.  That makes sense I guess you'd always need the standard title so you can search for it. Thanks Michael

**Comment by mjuarez2** [comment]
@nicholas-kebbas This is on https://pr-256-dgreat.pantheonsite.io/ Works as I tested it so I can just move it forward to master

**Comment by nicholas-kebbas** [comment]
@mjuarez2 Sounds good thanks Michael
