### ISSUE TITLE
System Files are private and not able to be opened

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#244]
Files with the /system/ alias give an error. This seems to happen with all the /system/ files. These files are also in the "private" folder when accessed through the WYSIWYG. /sites/default files work as expected.

https://live-dgreat.pantheonsite.io/system/files/isss/new-i-20-ds-2019-request-form.pdf
https://live-dgreat.pantheonsite.io/isss/students/j-1/leave-of-absence-withdrawal

**Comment by drmyers1** [comment]
@rjbain Here is another example of pdfs that are in system files and we are not able to access.

https://live-dgreat.pantheonsite.io/career-services/interviews-offers

Marlene and Tom found pages that had system files that were not in the system.  I still need to get you those examples.

**Comment by rjbain** [comment]
@drmyers1 I'm not having much luck with this. I tried using this module, but it's not working for me: 
https://www.drupal.org/project/private_files_download_permission

I found this issue and tried the fix mentioned in the comments, but it didn't work for me:
https://www.drupal.org/project/private_files_download_permission/issues/2918393

**Comment by drmyers1** [comment]
@mjuarez2 could you take a look at this request and see if you have any ideas.  @rjbain is stuck right now.

**Comment by mjuarez2** [comment]
@rjbain @drmyers1 @nicholas-kebbas Is the idea here to make specific files accessible only to certain roles?

**Comment by rjbain** [comment]
@mjuarez2 I think we just want to make them visible to everyone at the moment.

**Comment by drmyers1** [comment]
@mjuarez2 here is page where several links point the system/files pdfs.  everyone gets and error that they are not authorized the access.

https://live-dgreat.pantheonsite.io/management/intranet/accreditation

**Comment by drmyers1** [comment]
@mjuarez2 any updates on this?  any ideas for fixing this?

**Comment by mjuarez2** [comment]
@drmyers1 I don't have any suggestions here. Not sure why the files cannot be accessed, seems there is no drupal setting here. May be a server setting.
