### ISSUE TITLE
CAS Login to Dashboard

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#249]
@mjuarez2 were you able to link to the dashboard after the CAS login.

**Comment by drmyers1** [comment]
@mjuarez2 do you have an update on this?

**Comment by mjuarez2** [comment]
@drmyers1 Installed a module called redirect_after_login. Seems to work but need to be tested to make sure it doesn't interfere with groups assignment or any other post CAS login processes. It can be tested here: https://pr-259-dgreat.pantheonsite.io

**Comment by nicholas-kebbas** [comment]
@mjuarez2 Thanks Michael, it looks to work. Yeah, we'll need to wait to test CAS on Tuesday – once we're able to – before pushing this LIVE, then.

**Comment by mjuarez2** [comment]
@nicholas-kebbas @drmyers1 This is now on https://pr-273-dgreat.pantheonsite.io/

**Comment by drmyers1** [comment]
@mjuarez2 this worked for the test account i tested with.  i am not sure if we should push this up just yet since we have all kinds of errors showing up in new relic.
