### ISSUE TITLE
Adding a "Nick's" Link

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#253]
when you create a link a "Nick's" Link there is text at the top of the view.

https://live-dgreat.pantheonsite.io/node/add/favorite_link?edit[field_link_type][und]=quick?destination=favorite-links/allapps

The text reads as follows:
Creating a Link below will add it to your Quick Menu or Favorite Links on the dashboard. New submissions and changes will appear within about 5 minutes

Can we change this to the following
Creating a Link below will add it to your links on the dashboard.

Also there is text below the url box.  Can this be adjusted?  Here is the text:
Start typing the title of a piece of content to select it. You can also enter an internal path such as /node/add or an external URL such as http://example.com. Enter <front> to link to the front page. 

If we can adjust, can we include that for full url http:// or https:// must be included.  I dont think we need the following: You can also enter an internal path such as /node/add or an external URL such as http://example.com. Enter <front> to link to the front page. 

On save it brings you to the node view.  Can we change the on save behavior to redirect to the dashboard?  Here is an example of a Nick's link i created.
https://live-dgreat.pantheonsite.io/node/140222

**Comment by mjuarez2** [comment]
@nicholas-kebbas @drmyers1 I made some changes here: https://pr-256-dgreat.pantheonsite.io The text below the link can't be changed but some helper text can be added, which I did there.

**Comment by drmyers1** [comment]
@mjuarez2 this looks good.
