### ISSUE TITLE
Calendar Reset

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#257]
@mjuarez2 we got a report from Marlene that the reset button is working on the calendar search.  Can you take a look at this?

https://live-dgreat.pantheonsite.io/calendar

**Comment by mjuarez2** [comment]
@drmyers1 @nicholas-kebbas There might be browser/site caching. I set the query string arguments on the reset button explicitly so this might help. U can see this at https://pr-256-dgreat.pantheonsite.io

**Comment by drmyers1** [comment]
@mjuarez2 this looks like it is working.

**Comment by drmyers1** [comment]
@mjuarez2 @nicholas-kebbas i believe this got pushed out a while ago.  Can you confirm and I move the card to completed?

**Comment by mjuarez2** [comment]
@drmyers1 @nicholas-kebbas This is currently live
