### ISSUE TITLE
Announcements displaying roles

### ISSUE THREAD

**Issue by tomkhenke** [rjbain/dgreat#282]
Roles are now exposed on the Announcements detail page. This was not the case before going live.

Tags are not showing, but maybe live announcements have no tags?

**Comment by mjuarez2** [comment]
@tomkhenke @nicholas-kebbas @rjbain Fix for this is on https://pr-281-dgreat.pantheonsite.io/

**Comment by tomkhenke** [comment]
Here's a couple direct links to announcements:

https://pr-281-dgreat.pantheonsite.io/node/140238
https://pr-281-dgreat.pantheonsite.io/node/140239

Both seem to work good in Mac Chrome and Safari
