### ISSUE TITLE
New Site Map

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#294]
Create a new site map of myUSF to update search index

**Comment by rjbain** [comment]
@drmyers1 I'm looking into this. Just FYI, sitemaps have a performance impact, especially on large sites, due to needing to index so many pages, which usually happens when running cron.

**Comment by rjbain** [comment]
@drmyers1 Sure, we could do that. I'll get it set up and do a quick a/b test.

**Comment by rjbain** [comment]
@drmyers1 I'm running into errors when trying to generate the XML Sitemap. I'm looking for a possible fix, or alternative module.

**Comment by drmyers1** [comment]
@rjbain thanks for the update.  let me know if you need me to test anything as you make progress.

**Comment by rjbain** [comment]
@drmyers1 I was able to get another module to work. I have the sitemap up on this branch:
https://pr-301-dgreat.pantheonsite.io/sitemap.xml
I also have the robots.txt updated there, but it automatically gets replaced on non LIVE environments, so we won't see the changes until it's deployed.

**Comment by rjbain** [comment]
@drmyers1 This is pushed live, but the robots.txt didn't update. I'll have to follow up with pantheon support. I see the changes in the master repo, but not on the live site.

**Comment by rjbain** [comment]
@drmyers1 The robots.txt didn't update after I merged the new 404 page. I notified Pantheon support that re-merging didn't work and I'm checking with them to see if there'd be any issue with me just directly uploading the file to the live server via sftp.

**Comment by rjbain** [comment]
@drmyers1 The robots.txt is updated on live now.
