### ISSUE TITLE
My Links Issue

### ISSUE THREAD

**Issue by drmyers1** [rjbain/dgreat#312]
We have received several complaint that users are adding and managing their My Links.  The configuration changes and addition of new links only stays until the user logs out.  Once the user logs back in everything is out of order or links are no longer available.

If we are not able to find a quick solution for this we will need to communicate with users and remove the ability to add and manage until this is resolved.

**Comment by drmyers1** [comment]
@mjuarez2 @nicholas-kebbas we need to remove the add and manage buttons from the My Links section.  Also can you add some text at the top with the following message.

Add & manage are temporarily unavailable.

**Comment by drmyers1** [comment]
@mjuarez2 we should test if the search module is connected to the problems we are having with the My Links.  As part of your troubleshooting, can you test enabling the module on a multidev.  @rjbain mentioned that it didn't look like it installed correctly the first time.

**Comment by nicholas-kebbas** [comment]
@mjuarez2 @drmyers1 Michael's new dashboard changes are up here: https://pr-348-dgreat.pantheonsite.io/

I'm currently testing with all roles.

@mjuarez2 David is putting together the finalized list of Top Apps and myLinks to give to you.  Can these changes be done locally and pushed to production, or would these need to be added to production after the content type is pushed up?

**Comment by mjuarez2** [comment]
@nicholas-kebbas @drmyers1 We could push the views and content type up and add all the content and then push the dashboard template up when the content is ready.

**Comment by nicholas-kebbas** [comment]
@mjuarez2 @drmyers1 Sounds good michael, let's go with that.  Adding, removing, and editing these links seems to work so that's approved on my end.

**Comment by drmyers1** [comment]
@mjuarez2 @nicholas-kebbas i created the master list for both the top apps and the my links.  
https://docs.google.com/document/d/1K3pQDWDtvSOQKaPyjAFamyB5_5wTSBs8Q1OmTHDntpI/edit#

Please take a look and let me know if you have any feedback.

**Comment by mjuarez2** [comment]
@drmyers1 @nicholas-kebbas The content type and views are live
