### ISSUE TITLE
Batch Process adds new link, but link is hidden from view

### ISSUE THREAD

**Issue by nicholas-kebbas** [rjbain/dgreat#385]
When you add a new favorite app through the batch process, it adds the new link at a weight of -1000. If this weight is already occupied by another on the user's list, then they will not see the newly added link.

**Comment by labboy0276** [comment]
@nicholas-kebbas I can;t replicate.  When I add a new quick link via the defaults, it renders the right weight.  I pulled the DB from the live instance as a FYI.

Can you send me a screenshot of what fields you entered to get the results you got please

**Comment by nicholas-kebbas** [comment]
@labboy0276 
It looks to occur for users who haven't reordered since multiple default apps were added.

You should be able to replicate if you add two consecutively through the default operation without reordering. I also created a video since it's a bit tricky to show via screenshots.  But overall, if the user doesn't reorder between favorite link adds, the new link keeps adding at the same weight, thus hiding one of the links at that weight.  

In the video, the user has not reordered their links at all, but several have been added through the batch process. As they change the weight of each link, it shows an additional link. 
https://drive.google.com/file/d/1zEB9_xPoZOIO-3oyw6eE-8sQYi0876Vu/view?usp=sharing

![create_directory](https://user-images.githubusercontent.com/5649192/47308282-00f43980-d5e6-11e8-9fc8-ecebd235503d.png)
![add_directory](https://user-images.githubusercontent.com/5649192/47308303-09e50b00-d5e6-11e8-9248-e7f6afff17ba.png)
![directory_at_-1000](https://user-images.githubusercontent.com/5649192/47308308-0f425580-d5e6-11e8-8682-16ba46bff8fb.png)

One idea I had is that the user's weights table doesn't update when the batch runs, and only when a user saves their changes on the favorite links editing page, so a new max weight is never calculated, and thus the same weight is added for the next link added through the batch.
  
Either way let me know if you're still not able to replicate, and thanks for taking a look

**Comment by labboy0276** [comment]
@nicholas-kebbas is this still an issue since the batch mechanism is no more?

**Comment by nicholas-kebbas** [comment]
@labboy0276 Nope this is resolved since the important batch logic runs upon login now. I'll move the card
