### ISSUE TITLE
Groups Migration

### ISSUE THREAD

**Issue by reynoldsalec** [rjbain/dgreat#41]
**Technical Details**

- [x] Migrate the old OG groups into D8 Groups module

Note that there are references from the groups to the various Link entities to designate certain Links as default for a given Group. We can migrate this relationship in #42.

**Comment by labboy0276** [comment]
@reynoldsalec @rjbain see https://github.com/rjbain/dgreat/pull/50

I added a new module called dgreat_migration, installed and configured the group module & added the config for a csv migration of the d7 og group content type itself to d8 groups.  I attached the csv here as well.  We can add in via rsync later

https://www.dropbox.com/s/0ecqo33d3jhfzvt/migrate-og-to-groups.csv?dl=0
